apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-03
  description: "test api 03"
  annotations:
    github.com/project-slug: Fernanda-Duran-NTT/test-03
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: "Sandboxed" 
  owner: "guests"
  status: "Draft"
  type: openapi
  definition: 
    openapi: "3.0.0"
    info:
      version: "1.0.0"
      title: "Simple API"
      description: "A simple API to illustrate OpenAPI concepts"
    servers:
      - url: "https://example.com/v1"
    paths:
      /users:
        get:
          summary: "Get all users"
          responses:
            '200':
              description: "A list of users"
              content:
                application/json:
                  schema:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/User"
    components:
      schemas:
        User:
          type: "object"
          properties:
            id:
              type: "integer"
            name:
              type: "string"